name: Manual Release

on:
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  versioning:
    name: Bump Minor Version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest version
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate new minor version
        id: bump_patch
        run: |
          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
          IFS='-' read -r version suffix <<< "$latest_tag"
          IFS='.' read -r major minor patch labels <<< "$version"
          minor=$((minor + 1))
          new_version="$major.$minor.0-stable"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_patch.outputs.new_version }}
          git push origin ${{ steps.bump_patch.outputs.new_version }}

    outputs:
      version: ${{ steps.bump_patch.outputs.new_version }}

  release:
    needs: versioning
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.versioning.outputs.new_version }}
      tag_latest: true
    secrets:
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}

  publish:
    needs: [release, versioning]
    uses: ./.github/workflows/publish_version.yml
    with:
      version: ${{ needs.versioning.outputs.new_version }}
      build_number: ${{ github.run_number }}
      notes: ${{ github.event.head_commit.message }}
